language: node_js

node_js:
  - "8"

branches:
  only:
    - master

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    local_dir: .
    on:
      branch: master
